"""One runnable Python script per check, 1 through 8, built on the shared kernels.

The reliability decision changed. There is no longer a second statistics implementation
living in these templates. Every corrected number a script prints comes from
``redline.correction.kernels``, the same module the check runs in-process. Each emitted
script inlines that module's source text verbatim (via ``inspect.getsource``) and calls the
kernel with the injected parameters. The engine numbers, the preview, and the downloadable
script then agree by construction, because they are the same code running on the same data
with the same seed.

An emitted script is assembled from five parts, in order:

1. A shebang and a docstring naming the check, what it fixes, and how to run it.
2. ``from __future__ import annotations`` and the light imports (argparse, json).
3. The kernel module source, inlined verbatim. A scientist reading the script sees exactly
   the code Redline ran. The script imports nothing from ``redline``; it is standalone.
4. The injected parameter constants, each written with ``repr()`` so strings, lists, and
   ``None`` round-trip as valid Python literals.
5. A ``main()`` that parses ``--h5ad``, loads the AnnData, calls the kernel, prints a short
   human-readable report, and finally prints, as the last line of stdout:

       REDLINE_RESULT {"original": <n>, "corrected": <n>, ...}

   The JSON keys are exactly that check's ``Evidence.numbers`` keys, so the acceptance
   harness can execute the script and diff its output against what Redline reported. On an
   unsalvageable finding the kernel returns ``corrected: None`` and ``unsalvageable: True``,
   and the script prints exactly that. It never fabricates a number, because the branch
   lives in the kernel and the script prints what the kernel returned.

The parameterized tail is a ``string.Template`` with ``${braced}`` slots. A missing slot is
loud: ``substitute`` raises ``KeyError``. The kernel source is concatenated after the
substitution, not passed through it, so a literal ``$`` in scientific code (there is none
today) could never be mistaken for a slot.
"""

from __future__ import annotations

import inspect
from string import Template

from . import kernels

# ── the inlined kernel source ─────────────────────────────────────────────────────────
# The scripts are standalone, so ``from __future__ import annotations`` is hoisted to the
# top of every emitted file (a future import must be the first statement). It is stripped
# here and re-added by PREAMBLE, so it never appears twice.
_KERNEL_SRC = inspect.getsource(kernels).replace("from __future__ import annotations\n", "", 1)


def kernel_source() -> str:
    """The kernel module source, inlined verbatim into every emitted script."""
    return _KERNEL_SRC


# ── the standalone-script preamble (future import first, then the light imports) ──────
PREAMBLE = "from __future__ import annotations\n\nimport argparse\nimport json\n\n\n"

_HEAD = "#!/usr/bin/env python\n"

# ── per-check header docstrings ───────────────────────────────────────────────────────

HEADERS: dict[int, str] = {
    1: _HEAD + '''"""Pseudoreplication re-test. Generated by Redline.

Fixes a differential-expression claim that treated correlated cells as independent
observations. The kernel aggregates cells to one profile per replicate before testing, so
significance is not inflated by the number of cells.

Run:  python 01_pseudoreplication.py --h5ad <path>
"""
''',
    2: _HEAD + '''"""Double-dipping held-out re-test. Generated by Redline.

Fixes markers that were both discovered and tested on the same cells. The kernel splits the
counts into two independent halves by Poisson thinning, clusters on one half, and scores the
claimed markers on the other. This is a count-split held-out check, not a certified FDR
correction. ClusterDE (Song et al. 2023) is the stronger, purpose-built method.

Run:  python 02_double_dipping.py --h5ad <path>
"""
''',
    3: _HEAD + '''"""Clustering-fragility re-test. Generated by Redline.

Fixes a claim that rests on one clustering resolution. The kernel sweeps the resolution and
reports the share of settings where the claimed group survives as a discrete cluster.

Run:  python 03_fragility.py --h5ad <path>
"""
''',
    4: _HEAD + '''"""Confounding separability check. Generated by Redline.

Tests whether the effect of interest can be separated from a technical variable at all. When
they are perfectly nested no model can tell them apart, and the kernel reports no corrected
result rather than inventing one.

Run:  python 04_confounding.py --h5ad <path>
"""
''',
    5: _HEAD + '''"""Multiple-testing correction. Generated by Redline.

Fixes a hit count reported without controlling the false-discovery rate. The kernel re-tests
every gene at the replicate level, applies Benjamini-Hochberg (or Benjamini-Yekutieli) FDR
control, and reports how many raw hits survive.

Run:  python 05_multiple_testing.py --h5ad <path>
"""
''',
    6: _HEAD + '''"""Unmodeled-covariate re-test. Generated by Redline.

Fixes a comparison that left a covariate out of the model. The kernel fits both the naive
and the adjusted model at the same replicate level, so a cell-level p is never compared to a
unit-level p.

Run:  python 06_unmodeled_covariate.py --h5ad <path>
"""
''',
    7: _HEAD + '''"""Resolution-choice re-test. Generated by Redline.

Fixes a resolution picked without justification. The kernel sweeps the resolution on one
fixed embedding, scores each with the silhouette (or adjacent-pair stability), and reports
the range the data supports next to the value that was chosen.

Run:  python 07_resolution_choice.py --h5ad <path>
"""
''',
    8: _HEAD + '''"""Test-assumption re-test. Generated by Redline.

Fixes a normal-theory test applied to overdispersed counts. The kernel measures the
overdispersion, reproduces the claimed test as claimed, then re-runs the comparison with a
count-aware negative-binomial model.

Run:  python 08_test_assumptions.py --h5ad <path>
"""
''',
}

# ── per-check parameterized tails (constants, then main) ──────────────────────────────

_T01 = '''

# ── injected parameters (repr, so every literal round-trips) ──
H5AD = ${h5ad}
UNIT = ${unit}
GROUPING = ${grouping}
REF = ${ref}
ALT = ${alt}
GENE = ${gene}
COVARIATES = ${covariates}
ALPHA = ${alpha}


def main():
    ap = argparse.ArgumentParser(description="Honest pseudobulk re-test of a differential-expression claim.")
    ap.add_argument("--h5ad", default=H5AD)
    args = ap.parse_args()

    adata = _load(args.h5ad)
    result = check1_pseudoreplication(adata, UNIT, GROUPING, REF, ALT, GENE, list(COVARIATES or []), ALPHA)

    print("Redline pseudoreplication re-test")
    print("honest method:", result["method"])
    print("naive per-cell p:", result["original"], "over", result["n_cells"], "cells")
    print("honest per-replicate p:", result["corrected"], "over", result["n_units"], "replicate profiles")
    print("intra-unit ICC:", result["icc"], "(high means cells within a replicate are far from independent)")
    print("REDLINE_RESULT " + json.dumps(result))


if __name__ == "__main__":
    main()
'''

_T02 = '''

# ── injected parameters (repr, so every literal round-trips) ──
H5AD = ${h5ad}
GROUPING = ${grouping}
TARGET_GROUP = ${target_group}
MARKERS = ${markers}
SPLIT = ${split}
SEED = ${seed}


def main():
    ap = argparse.ArgumentParser(description="Held-out re-test of markers found by clustering.")
    ap.add_argument("--h5ad", default=H5AD)
    args = ap.parse_args()

    adata = _load(args.h5ad)
    result = check2_double_dipping(adata, GROUPING, TARGET_GROUP, list(MARKERS or []), SPLIT, SEED)

    print("Redline double-dipping held-out re-test")
    print("mean discovery AUC:", result["original"], "| mean held-out AUC:", result["corrected"])
    print("markers that survive on held-out cells:", result["surviving"], "of", len(MARKERS or []))
    for gene, r in result["markers"].items():
        print(" ", gene, "disc", r["disc"], "hold", r["hold"], "survives", r["survives"])
    # Count splitting is evidence, not a certified FDR fix. ClusterDE is the stronger method.
    print("REDLINE_RESULT " + json.dumps(result))


if __name__ == "__main__":
    main()
'''

_T03 = '''

# ── injected parameters (repr, so every literal round-trips) ──
# TRACK_COLUMN is left None so the kernel finds the obs column carrying the tracked group,
# deterministically. The module passes only the group name, matching its config.
H5AD = ${h5ad}
TRACK = ${track}
TRACK_COLUMN = None
R_MIN = ${min}
R_MAX = ${max}
R_STEP = ${step}
SEED = ${seed}


def main():
    ap = argparse.ArgumentParser(description="Track a claimed group across clustering resolutions.")
    ap.add_argument("--h5ad", default=H5AD)
    args = ap.parse_args()

    adata = _load(args.h5ad)
    result = check3_fragility(adata, TRACK, TRACK_COLUMN, R_MIN, R_MAX, R_STEP, SEED)

    print("Redline clustering-fragility re-test")
    print("tracked group:", TRACK)
    print("stability (share of resolutions where the group survives):", result["corrected"])
    print("present between resolutions", result["present_lo"], "and", result["present_hi"])
    for s in result["steps"]:
        print("  resolution", s["r"], "clusters", s["clusters"], "present", s["present"])
    print("REDLINE_RESULT " + json.dumps(result))


if __name__ == "__main__":
    main()
'''

_T04 = '''

# ── injected parameters (repr, so every literal round-trips) ──
H5AD = ${h5ad}
INTEREST = ${interest}
TECHNICAL = ${technical}
GENE = ${gene}
UNIT = ${unit}
ALPHA = ${alpha}


def main():
    ap = argparse.ArgumentParser(description="Test separability of an effect of interest from a technical variable.")
    ap.add_argument("--h5ad", default=H5AD)
    args = ap.parse_args()

    adata = _load(args.h5ad)
    result = check4_confounding(adata, INTEREST, TECHNICAL, GENE, UNIT, ALPHA)

    print("Redline confounding separability check")
    print("crosstab of", INTEREST, "against", TECHNICAL, "| Cramers V:", result["cramers_v"])
    if result["unsalvageable"]:
        print("The effect of interest and the technical variable are fully collinear.")
        print("No model can separate them from this data. Reporting no corrected result.")
    else:
        print("method:", result["method"])
        print("naive interest p (ignoring the technical variable):", result["original"])
        print("adjusted interest p (with the technical variable in the model):", result["corrected"])
    print("REDLINE_RESULT " + json.dumps(result))


if __name__ == "__main__":
    main()
'''

_T05 = '''

# ── injected parameters (repr, so every literal round-trips) ──
H5AD = ${h5ad}
UNIT = ${unit}
GROUPING = ${grouping}
REF = ${ref}
ALT = ${alt}
ALPHA = ${alpha}
METHOD = ${method}
TESTS = ${tests}


def main():
    ap = argparse.ArgumentParser(description="Apply FDR control across the per-gene tests.")
    ap.add_argument("--h5ad", default=H5AD)
    args = ap.parse_args()

    adata = _load(args.h5ad)
    result = check5_multiple_testing(adata, UNIT, GROUPING, REF, ALT, ALPHA, METHOD, TESTS)

    print("Redline multiple-testing correction")
    print("genes tested:", result["tests"], "| method:", METHOD, "| alpha:", result["alpha"])
    print("raw hits at p <", result["alpha"], ":", result["original"], "-> survive FDR control:", result["corrected"])
    for r in result["top"][:10]:
        print("  ", r["gene"], "p", r["p"], "q", r["q"], "survives", r["survives"])
    print("REDLINE_RESULT " + json.dumps(result))


if __name__ == "__main__":
    main()
'''

_T06 = '''

# ── injected parameters (repr, so every literal round-trips) ──
H5AD = ${h5ad}
INTEREST = ${interest}
COVARIATE = ${covariate}
REF = ${ref}
ALT = ${alt}
UNIT = ${unit}
GENE = ${gene}
ALPHA = ${alpha}


def main():
    ap = argparse.ArgumentParser(description="Re-test a comparison with an unmodeled covariate added.")
    ap.add_argument("--h5ad", default=H5AD)
    args = ap.parse_args()

    adata = _load(args.h5ad)
    result = check6_unmodeled_covariate(adata, INTEREST, COVARIATE, REF, ALT, UNIT, GENE, ALPHA)

    print("Redline unmodeled-covariate re-test")
    print("crosstab of", INTEREST, "against", COVARIATE, "| Cramers V:", result["cramersV"])
    print("method:", result["method"])
    print("interest p without the covariate:", result["original"])
    print("interest p with the covariate in the model:", result["corrected"])
    print("REDLINE_RESULT " + json.dumps(result))


if __name__ == "__main__":
    main()
'''

_T07 = '''

# ── injected parameters (repr, so every literal round-trips) ──
H5AD = ${h5ad}
R_MIN = ${min}
R_MAX = ${max}
R_STEP = ${step}
CRITERION = ${criterion}
CHOSEN = ${chosen}
SEED = ${seed}


def main():
    ap = argparse.ArgumentParser(description="Report the resolution range the data supports.")
    ap.add_argument("--h5ad", default=H5AD)
    args = ap.parse_args()

    adata = _load(args.h5ad)
    result = check7_resolution_choice(adata, R_MIN, R_MAX, R_STEP, CRITERION, CHOSEN, SEED)

    print("Redline resolution-choice re-test")
    print("criterion:", result["criterion"], "| chosen:", result["original"], "| criterion-optimal:", result["best"])
    print("supported range:", result["supportedLo"], "to", result["supportedHi"])
    print("coarsest resolution the evidence supports:", result["corrected"])
    for s in result["steps"]:
        print("  resolution", s["r"], "clusters", s["clusters"], "score", s["score"], "supported", s["present"])
    print("REDLINE_RESULT " + json.dumps(result))


if __name__ == "__main__":
    main()
'''

_T08 = '''

# ── injected parameters (repr, so every literal round-trips) ──
H5AD = ${h5ad}
GROUPING = ${grouping}
REF = ${ref}
ALT = ${alt}
UNIT = ${unit}
GENE = ${gene}
CLAIMED_TEST = ${claimed_test}
ALPHA = ${alpha}


def main():
    ap = argparse.ArgumentParser(description="Compare a normal-theory test to a count-aware model.")
    ap.add_argument("--h5ad", default=H5AD)
    args = ap.parse_args()

    adata = _load(args.h5ad)
    result = check8_test_assumptions(adata, GROUPING, REF, ALT, UNIT, GENE, CLAIMED_TEST, ALPHA)

    print("Redline test-assumptions re-test")
    print("claimed test:", CLAIMED_TEST, "| method:", result["method"])
    print("overdispersion (variance/mean, 1.0 is Poisson):", result["overdispersion"])
    print("claimed-test p:", result["original"])
    print("count-aware p:", result["corrected"])
    print("REDLINE_RESULT " + json.dumps(result))


if __name__ == "__main__":
    main()
'''

# ── assemble the tail templates ───────────────────────────────────────────────────────

TEMPLATES: dict[int, Template] = {
    1: Template(_T01),
    2: Template(_T02),
    3: Template(_T03),
    4: Template(_T04),
    5: Template(_T05),
    6: Template(_T06),
    7: Template(_T07),
    8: Template(_T08),
}

#: The exact slot set each script's tail expects. These are the parameter keys the module
#: must supply to ``render_corrected_code``. The names match what the module already passes
#: from its config, so the only new keys the module must add are the ones the kernel needs
#: and the config does not carry: check 4 adds ``gene``, ``unit`` and ``alpha``; checks 6
#: and 8 add ``gene``. The module resolves each and passes the same value to both the kernel
#: call and the injected constants (or ``None`` to both, since the kernel's gene picker is
#: deterministic and both sides then pick identically). Check 3's tracked-group column is
#: not a slot: the tail passes ``None`` and the kernel finds it deterministically.
SLOTS: dict[int, tuple[str, ...]] = {
    1: ("h5ad", "unit", "grouping", "ref", "alt", "gene", "covariates", "alpha"),
    2: ("h5ad", "grouping", "target_group", "markers", "split", "seed"),
    3: ("h5ad", "track", "min", "max", "step", "seed"),
    4: ("h5ad", "interest", "technical", "gene", "unit", "alpha"),
    5: ("h5ad", "unit", "grouping", "ref", "alt", "alpha", "method", "tests"),
    6: ("h5ad", "interest", "covariate", "ref", "alt", "unit", "gene", "alpha"),
    7: ("h5ad", "min", "max", "step", "criterion", "chosen", "seed"),
    8: ("h5ad", "grouping", "ref", "alt", "unit", "gene", "claimed_test", "alpha"),
}


def assemble(check_id: int, injected: dict[str, str]) -> str:
    """Build the full standalone script for ``check_id`` from already-repr'd ``injected``.

    The kernel source is concatenated after the tail substitution, never through it, so a
    ``$`` inside scientific code could not be read as a slot. ``substitute`` raises
    ``KeyError`` on a slot the injected map does not fill.
    """
    cid = int(check_id)
    tail = TEMPLATES[cid].substitute(injected)
    return HEADERS[cid] + PREAMBLE + kernel_source() + tail


__all__ = ["TEMPLATES", "SLOTS", "HEADERS", "PREAMBLE", "kernel_source", "assemble"]
